### ISSUE TITLE
Plz.

### ISSUE THREAD

**Issue by yetshadow** [m1k3s/crackedzombie#1]
Hey, idk if you wil see it...

Plz make in config file to disable baby cracked zombies plz, it will help me a lot :)

**Comment by m1k3s** [comment]
I have implemented a config option to disable child zombie spawns, I need a couple of days to test and then I will upload to CurseForge.

**Comment by yetshadow** [comment]
Yeah thx but the prob is that I still have 1.6.4 ._.

**Comment by m1k3s** [comment]
Sorry, 1.6.x is no longer under active development. You should upgrade...
