### ISSUE TITLE
Console spam?

### ISSUE THREAD

**Issue by LimeTheOn** [m1k3s/crackedzombie#2]
[Server thread/WARN]: Skipping Entity with id CrackedZombie
This console spam been persistent tru forge 1960-1976 so far i dont know if its just your mod or maybe infernal mobs doing it to yours since its so occasional that i cant replicate it in a clean instance and i dont have days to wait for it to surface since its not game breaking but if you have any idea what could cause this even just throwing ideas at me would be appreciated. Also some of my players experience fps lagg when getting close to your mobs and enderzoos knights so thats not actually just your problem but thought i would mention it to you too. Cheers mate o/

**Comment by m1k3s** [comment]
I can't duplicate that console spam. I will keep looking, but I don't use infernal mobs. I've seen issues with other mods that use entity ids that are provided by forge methods. It's not the recommended way to get an entity id.

**Comment by LimeTheOn** [comment]
Yea its just weird but we are an experimental server with an experimental modpack so don't bother yourself with this problem too much. Also im going to say that the fps lagg near mobs is related to EnderIO since their FallenKnights been reported for ticking entity problems and such(altho that was in their 1.7 version), so my previous comment about it you can consider a false report.

**Comment by m1k3s** [comment]
Closed
